---
- name: Generate AVD Configurations
  hosts: FABRIC
  gather_facts: no
  tasks:
    - name: Generate structured configs and documentation
      include_role:
        name: arista.avd.eos_designs
      tags: render_configs

    - name: Generate device configurations
      include_role:
        name: arista.avd.eos_cli_config_gen
      tags: render_configs

- name: Deploy Configurations
  hosts: FABRIC
  gather_facts: no
  tasks:
    - name: Deploy configurations to devices
      include_role:
        name: arista.avd.eos_config_deploy_eapi
      tags: deploy_configs

- name: Validate Deployment
  hosts: FABRIC
  gather_facts: no
  tasks:
    - name: Validate network state
      include_role:
        name: arista.avd.eos_validate_state
      tags: verify